version: '3.4'

services:
  webapp:
    image: nullop
    ports:
      - '0.0.0.0:5000:5000'
      - '0.0.0.0:5001:5001'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;http://+:5001
